---
- name: Install nginx
  apt: pkg=nginx state=present update_cache=yes
  become: yes

- name: Create nginx site config
  template: src=download-robomongo.conf.j2 dest=/etc/nginx/sites-available/{{app}}.conf
  become: yes
  tags:
    - nginx

- name: Create certificate and key files for HTTPS
  template: src={{item}} dest={{root}}/{{item}}
  with_items:
    - "star.robomongo.org.crt"
    - "star.robomongo.org.key"

- name: Link nginx site config
  file: src=/etc/nginx/sites-available/{{app}}.conf dest=/etc/nginx/sites-enabled/{{app}}.conf state=link
  become: yes
  tags:
    - nginx

- name: Reload nginx
  service: name=nginx state=reloaded
  become: yes
  tags:
    - nginx
